import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-1">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="VinceA"
                className="w-3/4 h-auto ml-10 my-10"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="A highly movitated and passionate Software developer"
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium mr-10">
                A highly motivated Software Developer with a Diploma in Software
                Engineering Technician and 5+ years of customer service
                experience. Proficient in C#, Java, JavaScript, Angular, React,
                Express, Node.js, SQL, MongoDB, Git, JIRA, Visual Studio Code,
                and Eclipse.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                   hover:bg-light hover:text-dark ml-5 border-2 border-solid border-transparent hover:border-dark"
                >
                  Resume <LinkArrow className={"w-g ml-1"} />
                </Link>
                <Link
                  href="mailto:dukev1989@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Contact Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
